import createClient, {type Middleware} from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

const authMiddleware: Middleware = {
    onRequest({ request }) {
        const accessToken = localStorage.getItem('musicfun-access-token');
        if (accessToken) {
            request.headers.set("Authorization", "Bearer " + accessToken);
        }

        return request;
    },
    onResponse({response}) {
        if (!response.ok) {
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }
    }
};

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: {
    'api-key': '1cf1c93f-a632-4f68-8636-65f3d33ae86c'
    }
});

client.use(authMiddleware);