import createClient, {type Middleware} from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

export const baseUrl = "https://musicfun.it-incubator.app/api/1.0/"
export const apiKey = '1cf1c93f-a632-4f68-8636-65f3d33ae86c'

let refreshPromise: Promise<void> | null = null;

function makeRefreshToken() {
    if (!refreshPromise) {
        refreshPromise = (async (): Promise<void> => {
            const refreshToken = localStorage.getItem('musicfun-refresh-token');
            if (!refreshToken) throw new Error('No refresh token');

            const response = await fetch(baseUrl + 'auth/refresh', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'API-KEY': apiKey
                },
                body: JSON.stringify({refreshToken})
            })

            if (!response.ok) {
                localStorage.removeItem('musicfun-access-token')
                localStorage.removeItem('musicfun-refresh-token')
                throw new Error('Failed to refresh token');
            }
            const data = await response.json();
            localStorage.setItem('musicfun-access-token', data.accessToken)
            localStorage.setItem('musicfun-refresh-token', data.refreshToken)
        })()

        refreshPromise.finally(() => refreshPromise = null);
        return refreshPromise;
    }
}


const authMiddleware: Middleware = {
    onRequest({ request }) {
        const accessToken = localStorage.getItem('musicfun-access-token');
        if (accessToken) {
            request.headers.set("Authorization", "Bearer " + accessToken);
        }

        // @ts-ignore
        request._retryRequest = request.clone();

        return request;
    },
    async onResponse({request, response}) {
        if (response.ok) return response;
        if (!response.ok && response.status !== 401) {
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }

        try {
            await makeRefreshToken();
            // @ts-ignore
            const originalRequest: Request = request._retryRequest
            const retryRequest = new Request(originalRequest, {headers: new Headers(originalRequest.headers)})
            retryRequest.headers.set("Authorization", "Bearer " + localStorage.getItem('musicfun-access-token'))
            return fetch(retryRequest);
        } catch {
            return response;
        }

    }
};

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: {
    'api-key': apiKey
    }
});

client.use(authMiddleware);