import createClient from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/", headers: {
    'api-key': '1cf1c93f-a632-4f68-8636-65f3d33ae86c'
    } });